### ISSUE TITLE
Blockly_uncompressed. Dynamic scripts injection issue

### ISSUE THREAD

**Issue by sgrebnov** [sgrebnov/blockly#1]
blockly_uncompressed.js

// Delete any existing Closure (e.g. Soy's nogoog_shim).
document.write('< script type="text/javascript">var goog = undefined;</script>');
// Load fresh Closure Library.
document.write('< script type="text/javascript" src="' + window.BLOCKLY_DIR +
    '/../closure-library-read-only/closure/goog/base.js"></script>');
document.write('< script type="text/javascript">window.BLOCKLY_BOOT()</script>');

window.BLOCKLY_BOOT() is executed before base.js is loaded => error alert. TODO: test + investigate

**Comment by VladimirTsyshnatiy** [comment]
not svgweb issue
