### ISSUE TITLE
Comments to blocks don't appear

### ISSUE THREAD

**Issue by VladimirTsyshnatiy** [sgrebnov/blockly#35]
1 Right click on block
2 Select add comment
3 No action on clicking the question mark

expected bubble with text editor

**Comment by VladimirTsyshnatiy** [comment]
svgweb doesn't support foreignObject and textarea.

**Comment by sgrebnov** [comment]
This api is not supported by native IE9/10 SVG rendering engine so it will be changed anyway, no reason to address it as part of this work. Closing...
