### ISSUE TITLE
Correct IE8 conditional scripts

### ISSUE THREAD

**Issue by sgrebnov** [sgrebnov/blockly#37]
1. Script must apply on IE8 only

```
  <!--TODO ie8 conditional or via blockly_(un)compressed.js -->
  <!--[if lte IE 8]-->
  <meta content="true" name="svg.render.forceflash" />
  <script type="text/javascript" src="../../polyfills/svgweb/src/svg.js"></script>
  <!--[endIE]-->
```

To test in IE9/10 user should manually add ?svg.render.forceflash=true
1. Current version is incorrectly processed in IE9

![untitled](https://f.cloud.github.com/assets/981580/1435420/ec4ad436-413d-11e3-927b-9c615528679e.png)

**Comment by VladimirTsyshnatiy** [comment]
fixed with loader script for svgweb
