### ISSUE TITLE
Remove unnecesary logging

### ISSUE THREAD

**Issue by sgrebnov** [sgrebnov/blockly#39]
Forcing Flash SVG viewer for this browser 
 FLASH: addEventListener: GUID not found: _24 
 FLASH: addEventListener: GUID not found: _25 
 org.svgweb.nodes::SVGGroupNode 
 org.svgweb.nodes::SVGGroupNode 
 org.svgweb.nodes::SVGGroupNode 
 org.svgweb.nodes::SVGGroupNode 
1. ok, should be there
   Forcing Flash SVG viewer for this browser 
2. Must be investigated 
   FLASH: addEventListener: GUID not found: _24 
   FLASH: addEventListener: GUID not found: _25 
3. To be removed
   org.svgweb.nodes::SVGGroupNode

**Comment by sgrebnov** [comment]
it seems item3 is already fixed in the latest version, but sometimes I see the following error message
SCRIPT65535: Unexpected call to method or property access. 
blockly_compressed.js, line 756 character 236

**Comment by VladimirTsyshnatiy** [comment]
Don't found side effects of this messages. Probably it some temporary svg content
